---
name: Tests

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: Tests with Go ${{ matrix.golang }}
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        golang: ["1.20", "1.21.x"]

    steps:
      - uses: actions/checkout@v3.2.0

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.golang }}

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: ./bin/test
